---
  - name: Install Docker
    hosts: nodes
    become: yes

    tasks:
        - name: Update package cache
          apt:
            update_cache: yes
            upgrade: yes
        - name: Install tools
          apt:
            package: "{{ item }}"
            state: present
            update_cache: yes
          with_items:
            - git
            - curl
            - ca-certificates
        - name: Install Docker
          shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod +x get-docker.sh && sh ./get-docker.sh
        - name: Add User to Docker group
          user:
            name: ubuntu
            append: yes
            groups: docker
        - name: Install docker-compose
          get_url:
            url: https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 'u+x,g+x'
        - name: Change file ownership, group and permissions
          ansible.builtin.file:
            path: /usr/local/bin/docker-compose
            owner: ubuntu
            group: ubuntu
        - name: Reboot host and wait for it to restart
          reboot:
            msg: "Reboot"
            connect_timeout: 5
            reboot_timeout: 600
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: whoami